spring:
  cloud:
    config:
      server:
        git:
          uri: "${GIT_URI:https://github.com/herman-87/ph-allconfig.git}"
          default-label: "master"
          search-paths:
            - "config"
          clone-on-start: true
          basedir: ${CONFIG_REPO_PATH:/app/config-repo}
server:
  port: "${SERVER_PORT:8081}"