# Common security config
security:
  cors:
    allowed-origins: "*"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
    allowed-headers: "*"
    allow-credentials: false
    max-age: 3600

# Common logging/tracing
management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT}
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    root: INFO
    com.h87: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.client: DEBUG
    org.springframework.http.client: DEBUG
    org.springframework.security: DEBUG