spring:
  application:
    name: "${SPRING_APPLICATION_NAME:gateway}"
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 30s
      discovery:
        locator:
          enabled: false
      routes:
         - id: user
           uri: lb://user
           predicates:
             - Path=/user/**
           filters:
             - RewritePath=/user/(?<segment>.*), /${segment}
         - id: pharmafind
           uri: lb://pharmafind
           predicates:
             - Path=/pharmafind/**
           filters:
             - RewritePath=/pharmafind/(?<segment>.*), /${segment}
         - id: image
           uri: lb://image
           predicates:
             - Path=/image/**
           filters:
             - RewritePath=/image/(?<segment>.*), /${segment}
         - id: backoffice
           uri: lb://backoffice
           predicates:
             - Path=/backoffice/**
           filters:
             - RewritePath=/backoffice/(?<segment>.*), /${segment}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://ph-discovery-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

server:
  port: "${SERVER_PORT:8083}"

logging:
  level:
    com.ph.gateway: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.web: INFO
    reactor.netty: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,routes,loggers,metrics
  endpoint:
    gateway:
      enabled: true
